project:
  type: website
  render: 
    - "*.qmd"
    - "!DT_R_ver.qmd"
    - "!indexx.qmd"
    - "!index_dashboard.qmd"
    - "!*.ipynb/"

website:
  title: ""
  reader-mode: false
  open-graph: true
  navbar:
    background: "#1f4eb6"
    
    left:
      - href: index.qmd
        text: "{{< iconify mdi:home inline size=20px >}}Home"
      - href: about.qmd
        text: 'About'
      - href: tutorials.qmd
        text: 'Tutorials'

      - text: 'ConnectomeDB'
        menu:
         - href: database/human.qmd
           text: Human LR Pairs
         - href: database/mouseOrth.qmd
           text: Mouse Orthologs
         - href: database/Other/ratOrth.qmd
           text: Other Species

    right:
      - url: mailto:bioinfo@yokohama-cu.ac.jp
        text: "{{< iconify mdi:email inline size=20px >}}"
      #- icon: github
      #  menu:
      #    - text: Source Code
      #      href: https://github.com/bioinfo-YCU/ConnectomeDB
      #    - text: Report a Bug
      #      href: https://github.com/bioinfo-YCU/ConnectomeDB

  page-footer:
    left: '©2024 <a href="https://www-user.yokohama-cu.ac.jp/~bioinfo/hp/" target="_blank">YCU Bioinformatics Lab</a> | <a href="https://perkins.org.au/research/labs/cancer-program/systems-biology-and-genomics-overview/" target="_blank">Perkins Systems Biology & Genomics Lab</a>'
    right: "[Terms & Conditions](https://comp.med.yokohama-cu.ac.jp/collab/connectomeDB/policy.html)"
format:
  html:
    toc: true
    theme: default
    css: css/styles.css
    embed-resources: true  # Ensures resources are embedded for standalone
    grid: 
      body-width: 2500px
      sidebar-width: 0px
      margin-width: 0px

#header-includes: |
#  <script src="js/external_links.js"></script>
#  <script src="js/checkboxAndPopUp.js"></script>
#  <script src="js/themeSwitcher.js"></script>
#  <script src="js/adjustTableTextColor.js"></script>

