project:
  type: website
  render: 
    - "*.qmd"
    - "!DT_R_ver.qmd"
    - "!index_dashboard.qmd"
    - "!*.ipynb/"

website:
  title: ""
  reader-mode: true
  open-graph: true
  navbar:
    left:
      - text: ""
      - href: index.qmd
        text: '{{< fa regular house >}} Home'
      - href: database.qmd
        text: '{{< fa regular database >}} ConnectomeDB'
      - href: documentation.qmd
        text: '{{< fa regular book >}} Documentation'
      - href: citeus.qmd
        text: 'Cite Us!'
        
    right:
      - url: mailto:bioinfo@yokohama-cu.ac.jp
        text: '{{< fa regular envelope >}}'
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/bioinfo-YCU/ConnectomeDB
          - text: Report a Bug
            href: https://github.com/bioinfo-YCU/ConnectomeDB

  page-footer:
    right: "Page built with <a href='https://quarto.org/' target='_blank'>Quarto</a>  & Biorender Images"
    left: "©2024 [YCU Bioinformatics Lab](https://www-user.yokohama-cu.ac.jp/~bioinfo/hp/) | [Perkins Systems Biology & Genomics Lab](https://perkins.org.au/research/labs/cancer-program/systems-biology-and-genomics-overview/)"
    background: "#F7F7F7"

typography:
  fonts:
    - family: Roboto
      source: google

format:
  html:
    toc: true
    theme: cosmo
    css: css/styles.css
    embed-resources: true  # Ensures resources are embedded for standalone
    grid: 
      body-width: 2500px
      sidebar-width: 0px
      margin-width: 0px

filter: fontawesome

header-includes: |
  <script src="js/external_links.js"></script>
  <script src="js/checkboxAndPopUp.js"></script>
  <script src="js/themeSwitcher.js"></script>
  <script src="js/adjustTableTextColor.js"></script>





