project:
  type: website
  render: 
    - "*.qmd"
    - "!DT_R_ver.qmd"
    - "!index_*.qmd"
    - "!*.ipynb/"
    - "!database/human-trip.qmd"
    - "!stats-withAnnotations.qmd"
    - "!stats.qmd"
    - "!annotations/*.qmd"
    - "!database/human-trip*.qmd"
    - "!database/human-FilterOnTop.qmd"
    - "!askAIchat.qmd"
    - "!database/human_*.qmd"
    - "!database/qmd_template/*.qmd"
    
  post-render: 
    - "python src/remove_footer.py"
    - "python src/render_table.py"
    - "python src/render_Orthtable.py"

resources:
  - images
  - HTML
  - JSON
  
website:
  title: "ConnectomeDB2025"

  reader-mode: false
  open-graph: true
  navbar:
    # logo: images/LRmascot.webp
    background: "#1f4eb6"
    search: false
    
    left:
      - text: 'Documentation'
        menu:
         - href: docs/policy.qmd
           text: 'Terms & Conditions'
         - href: docs/about.qmd
           text: 'Introduction'
         - href: docs/methods.qmd
           text: 'Methods'
         - href: docs/tutorials.qmd
           text: 'Tutorials'
         - href: docs/updates.qmd
           text: 'Updates'
         - href: docs/help.qmd
           text: 'HELP'

           
      - text: 'Ligand-Receptor Browser'
        menu:
         - href: database/human.qmd
           text: '**Human LR Pairs**'
         # - href: database/human-trip.qmd
         #   text: Human LR Pairs ˣ Pubmed
         - href: database/mouseOrth.qmd
           text: '**Mouse Orthologs**'
         - href: database/other/chimpOrth.qmd
           text: 'Chimp Orthologs' 
         - href: database/other/macaqueOrth.qmd
           text: 'Macaque Orthologs' 
         - href: database/other/marmosetOrth.qmd
           text: 'Marmoset Orthologs' 
         - href: database/other/ratOrth.qmd
           text: 'Rat Orthologs' 
         - href: database/other/pigOrth.qmd
           text: 'Pig Orthologs' 
         - href: database/other/cowOrth.qmd
           text: 'Cow Orthologs' 
         - href: database/other/dogOrth.qmd
           text: 'Dog Orthologs' 
         - href: database/other/horseOrth.qmd
           text: 'Horse Orthologs' 
         - href: database/other/sheepOrth.qmd
           text: 'Sheep Orthologs' 
         - href: database/other/chickenOrth.qmd
           text: 'Chicken Orthologs' 
         - href: database/other/frogOrth.qmd
           text: 'Frog Orthologs' 
         - href: database/other/zebrafishOrth.qmd 
           text: 'Zebrafish Orthologs' 
           
      - href: downloads.qmd
        text: 'Downloads'
        
    # - href: askAIchat.qmd
    #   text: 'Ask AI chatbot'
        
     
      # - text: 'Annotations Browser'
      #   menu:
      #    - href: annotations/disease.qmd
      #      text: Diseases
      #    - href: annotations/pathway.qmd
      #      text: Pathways
      #    - href: annotations/ligand_group.qmd
      #      text: Ligand Lineage
      #    - href: annotations/receptor_group.qmd
      #      text: Receptor Lineage
      # - href: stats.qmd
      #   text: "{{< iconify mdi:chart-bar inline size=20px >}}Statistics"
    right:
#       - url: "updates.qmd"
#         text: "{{< iconify mdi:update inline >}}"
      - url: "help@connectomedb.org,alistair.forrest@perkins.uwa.edu.au,rui.hou@uwa.edu.au"
        text: "{{< iconify mdi:email inline >}}"

      - icon: github
        menu:
          - text: Source Code (upon publication)
            href: https://github.com/bioinfo-YCU/ConnectomeDB
          - text: Report a Bug
            href: https://github.com/bioinfo-YCU/ConnectomeDB

  page-footer:
    left: '©2025 <a href="https://www-user.yokohama-cu.ac.jp/~bioinfo/hp/" target="_blank">YCU Bioinformatics</a> | <a href="https://perkins.org.au/research/labs/cancer-program/systems-biology-and-genomics-overview/" target="_blank">Perkins Systems Biology & Genomics</a>'
    right: "[Terms & Conditions](https://comp.med.yokohama-cu.ac.jp/collab/connectomeDB/policy.html)"
format:
  html:
    toc: true
    theme: default
    css: css/styles.css
    # page-footer: false
    embed-resources: false  # Ensures resources are embedded for standalone
    grid: 
      body-width: 2500px
      sidebar-width: 0px
      margin-width: 0px
    

#header-includes: 
#  <script src="js/checkboxAndPopUp.js"></script>
#  <script src="js/themeSwitcher.js"></script>
#  <script src="js/adjustTableTextColor.js"></script>

