project:
  type: website
  render: 
    - "*.qmd"
    - "!DT_R_ver.qmd"
    - "!*.ipynb/"

website:
  title: ""
  reader-mode: true
  open-graph: true
  navbar:
    left:
      - text: "ConnectomeDB"
      - href: index.qmd
        text: Home
      # - href: DT_R_ver.qmd
      #   text: DT in R
      - href: database.qmd
        text: Database
    right:
      - href: https://www-user.yokohama-cu.ac.jp/~bioinfo/hp/
        text: YCU Bioinformatics Lab 
      - text: "|"
      - href: https://perkins.org.au/research/labs/cancer-program/systems-biology-and-genomics-overview/
        text: Perkins Systems Biology & Genomics Lab
      - icon: github
        href: https://github.com/bioinfo-YCU

  page-footer:
    right: "Page built with [Quarto](https://quarto.org/)"
    left: "© Copyright 2024 YCU Bioinformatics Lab | Perkins Systems Biology & Genomics Lab"
    background: "#F7F7F7"

format:
  html:
    toc: true
    theme: cerulean
    css: css/styles.css
    embed-resources: true  # Ensures resources are embedded for standalone
    grid: 
      body-width: 2500px
      sidebar-width: 0px
      margin-width: 0px

filter: fontawesome

header-includes: |
  <script src="js/checkboxAndPopUp.js"></script>
  <script src="js/themeSwitcher.js"></script>
  <script src="js/adjustTableTextColor.js"></script>
  <div id="theme-switcher">
    <label for="theme-select"><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Choose Theme:</label>
    <select id="theme-select" onchange="changeTheme()">
      <option value="cerulean">Cerulean</option>
      <option value="sketchy">Sketchy</option>
      <option value="spacelab">SpaceLab</option>
      <option value="cosmo">Cosmo</option>
      <option value="sandstone">Sandstone</option>
      <option value="flatly">Flatly</option>
      <option value="minty">Minty</option>
      <option value="paper">Paper</option>
      <option value="united">United</option>
    </select>
  </div>




