project:
  type: website
  output-dir: _site
  render: 
    - "*.qmd"
    - "browse.qmd"
    - "!*.ipynb/"
    - "!database/human-trip.qmd"
    - "!annotations/*.qmd"
    - "!database/qmd_template/*.qmd"
    
  post-render: 
    - "python src/remove_footer.py"
    - "python src/render_table.py"
    - "python src/render_Orthtable.py"

resources:
  - images
  - HTML
  - JSON
  - downloads
  
website:
  title: "ConnectomeDB2025"

  reader-mode: false
  open-graph: true
  navbar:
    # logo: images/LRmascot.webp
    background: "#1f4eb6"
    search: false
    
    left:
      - text: 'Documentation'
        menu:
         - href: docs/policy.qmd
           text: 'Terms & Conditions'
         - href: docs/about.qmd
           text: 'Introduction'
         - href: docs/methods.qmd
           text: 'Methods'
         - href: docs/tutorials.qmd
           text: 'Tutorials'
         - href: docs/updates.qmd
           text: 'Updates'
         - href: docs/help.qmd
           text: 'Help'

           
      - text: 'Ligand-Receptor Browser'
        menu:
         - href: database/human.qmd
           text: '**Human LR Pairs**'
         # - href: database/human-trip.qmd
         #   text: Human LR Pairs ˣ Pubmed
         - href: database/mouseOrth.qmd
           text: '**Mouse LR Pairs**'
         - href: database/other/chimpOrth.qmd
           text: 'Chimp LR Pairs' 
         - href: database/other/macaqueOrth.qmd
           text: 'Macaque LR Pairs' 
         - href: database/other/marmosetOrth.qmd
           text: 'Marmoset LR Pairs' 
         - href: database/other/ratOrth.qmd
           text: 'Rat LR Pairs' 
         - href: database/other/pigOrth.qmd
           text: 'Pig LR Pairs' 
         - href: database/other/cowOrth.qmd
           text: 'Cow LR Pairs' 
         - href: database/other/dogOrth.qmd
           text: 'Dog LR Pairs' 
         - href: database/other/horseOrth.qmd
           text: 'Horse LR Pairs' 
         - href: database/other/sheepOrth.qmd
           text: 'Sheep LR Pairs' 
         - href: database/other/chickenOrth.qmd
           text: 'Chicken LR Pairs' 
         - href: database/other/frogOrth.qmd
           text: 'Frog LR Pairs' 
         - href: database/other/zebrafishOrth.qmd 
           text: 'Zebrafish LR Pairs' 
           
      - href: downloads.qmd
        text: 'Downloads'
        
    # - href: askAIchat.qmd
    #   text: 'Ask AI chatbot'
        
     
      # - text: 'Annotations Browser'
      #   menu:
      #    - href: annotations/disease.qmd
      #      text: Diseases
      #    - href: annotations/pathway.qmd
      #      text: Pathways
      #    - href: annotations/ligand_group.qmd
      #      text: Ligand Lineage
      #    - href: annotations/receptor_group.qmd
      #      text: Receptor Lineage
      # - href: stats.qmd
      #   text: "{{< iconify mdi:chart-bar inline size=20px >}}Statistics"
    right:
      - url: "https://connectomedb.org/docs/about.html#cite-us"
        text: "{{< iconify mdi:information inline title='Citation information' >}}"
        
      - url: "mailto:&#104;&#101;&#108;&#112;&#64;&#99;&#111;&#110;&#110;&#101;&#99;&#116;&#111;&#109;&#101;&#100;&#98;&#46;&#111;&#114;&#103;,&#97;&#108;&#105;&#115;&#116;&#97;&#105;&#114;&#46;&#102;&#111;&#114;&#114;&#101;&#115;&#116;&#64;&#112;&#101;&#114;&#107;&#105;&#110;&#115;&#46;&#117;&#119;&#97;&#46;&#101;&#100;&#117;&#46;&#97;&#117;"
        text: "{{< iconify mdi:email inline title='Click to email directly' >}}"

      - icon: github
        menu:
          - text: Source Code (upon publication)
            href: https://github.com/bioinfo-YCU/ConnectomeDB
          - text: Report a Bug
            href: https://github.com/bioinfo-YCU/ConnectomeDB

  page-footer:
    left: '©2025 <a href="https://www-user.yokohama-cu.ac.jp/~bioinfo/hp/" target="_blank">YCU Bioinformatics</a> | <a href="https://perkins.org.au/research/labs/cancer-program/systems-biology-and-genomics-overview/" target="_blank">Perkins Systems Biology & Genomics</a>'
    right: "[Terms & Conditions](https://connectomedb.org/docs/policy.html)"
format:
  html:
    toc: true
    theme: default
    css: css/styles.css
    # page-footer: false
    embed-resources: false  # Ensures resources are embedded for standalone
    grid: 
      body-width: 2500px
      sidebar-width: 0px
      margin-width: 0px
    

# header-includes: 
#  <script src="js/checkboxAndPopUp.js"></script>
#  <script src="js/themeSwitcher.js"></script>
#  <script src="js/adjustTableTextColor.js"></script>

