project:
  type: website
  render: 
    - "*.qmd"
    - "!DT_R_ver.qmd"
    - "!index_dashboard.qmd"
    - "!*.ipynb/"

website:
  title: ""
  reader-mode: true
  open-graph: true
  navbar:
    background: "#1f4eb6"
    left:
      - href: index.qmd
        text: "{{< iconify mdi:home inline size=20px >}}Home"
      - href: about.qmd
        text: 'About'
      - href: database-human.qmd
        text: 'ConnectomeDB'
      - href: citeus.qmd
        text: "Cite Us!"

    right:
      - url: mailto:bioinfo@yokohama-cu.ac.jp
        text: "{{< iconify mdi:email inline size=20px >}}"
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/bioinfo-YCU/ConnectomeDB
          - text: Report a Bug
            href: https://github.com/bioinfo-YCU/ConnectomeDB

  page-footer:
    left: "©2024 [YCU Bioinformatics Lab](https://www-user.yokohama-cu.ac.jp/~bioinfo/hp/) | [Perkins Systems Biology & Genomics Lab](https://perkins.org.au/research/labs/cancer-program/systems-biology-and-genomics-overview/)"
    right: "[Terms & Conditions](policy.qmd)"

format:
  html:
    toc: true
    theme: default
    css: css/styles.css
    embed-resources: true  # Ensures resources are embedded for standalone
    grid: 
      body-width: 2500px
      sidebar-width: 0px
      margin-width: 0px

header-includes: |
  <script src="js/external_links.js"></script>
  <script src="js/checkboxAndPopUp.js"></script>
  <script src="js/themeSwitcher.js"></script>
  <script src="js/adjustTableTextColor.js"></script>


